// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: distri/v1/capability.proto

package distriv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapabilityReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Hostname        string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os              string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch            string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Compute         *ComputeCapability     `protobuf:"bytes,6,opt,name=compute,proto3" json:"compute,omitempty"`
	Network         *NetworkCapability     `protobuf:"bytes,7,opt,name=network,proto3" json:"network,omitempty"`
	Dynamic         *DynamicMetrics        `protobuf:"bytes,8,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
	UserPolicy      *UserPolicy            `protobuf:"bytes,9,opt,name=user_policy,json=userPolicy,proto3" json:"user_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilityReport) Reset() {
	*x = CapabilityReport{}
	mi := &file_distri_v1_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityReport) ProtoMessage() {}

func (x *CapabilityReport) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityReport.ProtoReflect.Descriptor instead.
func (*CapabilityReport) Descriptor() ([]byte, []int) {
	return file_distri_v1_capability_proto_rawDescGZIP(), []int{0}
}

func (x *CapabilityReport) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CapabilityReport) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *CapabilityReport) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CapabilityReport) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *CapabilityReport) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *CapabilityReport) GetCompute() *ComputeCapability {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *CapabilityReport) GetNetwork() *NetworkCapability {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *CapabilityReport) GetDynamic() *DynamicMetrics {
	if x != nil {
		return x.Dynamic
	}
	return nil
}

func (x *CapabilityReport) GetUserPolicy() *UserPolicy {
	if x != nil {
		return x.UserPolicy
	}
	return nil
}

type ComputeCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CPUInfo               `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu           *GPUInfo               `protobuf:"bytes,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Memory        *MemoryInfo            `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeCapability) Reset() {
	*x = ComputeCapability{}
	mi := &file_distri_v1_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeCapability) ProtoMessage() {}

func (x *ComputeCapability) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeCapability.ProtoReflect.Descriptor instead.
func (*ComputeCapability) Descriptor() ([]byte, []int) {
	return file_distri_v1_capability_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeCapability) GetCpu() *CPUInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *ComputeCapability) GetGpu() *GPUInfo {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *ComputeCapability) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

type CPUInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Model           string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	CoresPhysical   uint32                 `protobuf:"varint,2,opt,name=cores_physical,json=coresPhysical,proto3" json:"cores_physical,omitempty"`
	CoresLogical    uint32                 `protobuf:"varint,3,opt,name=cores_logical,json=coresLogical,proto3" json:"cores_logical,omitempty"`
	FrequencyMhz    uint32                 `protobuf:"varint,4,opt,name=frequency_mhz,json=frequencyMhz,proto3" json:"frequency_mhz,omitempty"`
	IsaFeatures     []string               `protobuf:"bytes,5,rep,name=isa_features,json=isaFeatures,proto3" json:"isa_features,omitempty"`               // ["AVX2", "FMA", "NEON", ...]
	BenchmarkGflops float64                `protobuf:"fixed64,6,opt,name=benchmark_gflops,json=benchmarkGflops,proto3" json:"benchmark_gflops,omitempty"` // Empirically measured
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CPUInfo) Reset() {
	*x = CPUInfo{}
	mi := &file_distri_v1_capability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUInfo) ProtoMessage() {}

func (x *CPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_capability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUInfo.ProtoReflect.Descriptor instead.
func (*CPUInfo) Descriptor() ([]byte, []int) {
	return file_distri_v1_capability_proto_rawDescGZIP(), []int{2}
}

func (x *CPUInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CPUInfo) GetCoresPhysical() uint32 {
	if x != nil {
		return x.CoresPhysical
	}
	return 0
}

func (x *CPUInfo) GetCoresLogical() uint32 {
	if x != nil {
		return x.CoresLogical
	}
	return 0
}

func (x *CPUInfo) GetFrequencyMhz() uint32 {
	if x != nil {
		return x.FrequencyMhz
	}
	return 0
}

func (x *CPUInfo) GetIsaFeatures() []string {
	if x != nil {
		return x.IsaFeatures
	}
	return nil
}

func (x *CPUInfo) GetBenchmarkGflops() float64 {
	if x != nil {
		return x.BenchmarkGflops
	}
	return 0
}

type GPUInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vendor           string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"` // "nvidia", "amd", "intel", "arm", "qualcomm"
	Model            string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	VramMb           uint64                 `protobuf:"varint,3,opt,name=vram_mb,json=vramMb,proto3" json:"vram_mb,omitempty"`
	ComputeUnits     uint32                 `protobuf:"varint,4,opt,name=compute_units,json=computeUnits,proto3" json:"compute_units,omitempty"`
	FrequencyMhz     uint32                 `protobuf:"varint,5,opt,name=frequency_mhz,json=frequencyMhz,proto3" json:"frequency_mhz,omitempty"`
	OpenclVersion    string                 `protobuf:"bytes,6,opt,name=opencl_version,json=openclVersion,proto3" json:"opencl_version,omitempty"` // "OpenCL 3.0" etc.
	OpenclDeviceName string                 `protobuf:"bytes,7,opt,name=opencl_device_name,json=openclDeviceName,proto3" json:"opencl_device_name,omitempty"`
	BenchmarkGflops  float64                `protobuf:"fixed64,8,opt,name=benchmark_gflops,json=benchmarkGflops,proto3" json:"benchmark_gflops,omitempty"` // Empirically measured
	Available        bool                   `protobuf:"varint,9,opt,name=available,proto3" json:"available,omitempty"`                                     // false if GPU exists but OpenCL unavailable
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GPUInfo) Reset() {
	*x = GPUInfo{}
	mi := &file_distri_v1_capability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfo) ProtoMessage() {}

func (x *GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_capability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfo.ProtoReflect.Descriptor instead.
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return file_distri_v1_capability_proto_rawDescGZIP(), []int{3}
}

func (x *GPUInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPUInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUInfo) GetVramMb() uint64 {
	if x != nil {
		return x.VramMb
	}
	return 0
}

func (x *GPUInfo) GetComputeUnits() uint32 {
	if x != nil {
		return x.ComputeUnits
	}
	return 0
}

func (x *GPUInfo) GetFrequencyMhz() uint32 {
	if x != nil {
		return x.FrequencyMhz
	}
	return 0
}

func (x *GPUInfo) GetOpenclVersion() string {
	if x != nil {
		return x.OpenclVersion
	}
	return ""
}

func (x *GPUInfo) GetOpenclDeviceName() string {
	if x != nil {
		return x.OpenclDeviceName
	}
	return ""
}

func (x *GPUInfo) GetBenchmarkGflops() float64 {
	if x != nil {
		return x.BenchmarkGflops
	}
	return 0
}

func (x *GPUInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type MemoryInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalRamMb     uint64                 `protobuf:"varint,1,opt,name=total_ram_mb,json=totalRamMb,proto3" json:"total_ram_mb,omitempty"`
	AvailableRamMb uint64                 `protobuf:"varint,2,opt,name=available_ram_mb,json=availableRamMb,proto3" json:"available_ram_mb,omitempty"`
	BandwidthGbS   float64                `protobuf:"fixed64,3,opt,name=bandwidth_gb_s,json=bandwidthGbS,proto3" json:"bandwidth_gb_s,omitempty"` // Estimated
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_distri_v1_capability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_capability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_distri_v1_capability_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryInfo) GetTotalRamMb() uint64 {
	if x != nil {
		return x.TotalRamMb
	}
	return 0
}

func (x *MemoryInfo) GetAvailableRamMb() uint64 {
	if x != nil {
		return x.AvailableRamMb
	}
	return 0
}

func (x *MemoryInfo) GetBandwidthGbS() float64 {
	if x != nil {
		return x.BandwidthGbS
	}
	return 0
}

type NetworkCapability struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	InterfaceType           string                 `protobuf:"bytes,1,opt,name=interface_type,json=interfaceType,proto3" json:"interface_type,omitempty"`  // "wifi", "ethernet"
	BandwidthMbps           uint32                 `protobuf:"varint,2,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"` // Estimated
	LatencyMsToOrchestrator float64                `protobuf:"fixed64,3,opt,name=latency_ms_to_orchestrator,json=latencyMsToOrchestrator,proto3" json:"latency_ms_to_orchestrator,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NetworkCapability) Reset() {
	*x = NetworkCapability{}
	mi := &file_distri_v1_capability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCapability) ProtoMessage() {}

func (x *NetworkCapability) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_capability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCapability.ProtoReflect.Descriptor instead.
func (*NetworkCapability) Descriptor() ([]byte, []int) {
	return file_distri_v1_capability_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkCapability) GetInterfaceType() string {
	if x != nil {
		return x.InterfaceType
	}
	return ""
}

func (x *NetworkCapability) GetBandwidthMbps() uint32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *NetworkCapability) GetLatencyMsToOrchestrator() float64 {
	if x != nil {
		return x.LatencyMsToOrchestrator
	}
	return 0
}

type DynamicMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUtilizationPct  float64                `protobuf:"fixed64,1,opt,name=cpu_utilization_pct,json=cpuUtilizationPct,proto3" json:"cpu_utilization_pct,omitempty"`
	GpuUtilizationPct  float64                `protobuf:"fixed64,2,opt,name=gpu_utilization_pct,json=gpuUtilizationPct,proto3" json:"gpu_utilization_pct,omitempty"`
	MemoryUsedPct      float64                `protobuf:"fixed64,3,opt,name=memory_used_pct,json=memoryUsedPct,proto3" json:"memory_used_pct,omitempty"`
	BatteryPct         float64                `protobuf:"fixed64,4,opt,name=battery_pct,json=batteryPct,proto3" json:"battery_pct,omitempty"`
	Charging           bool                   `protobuf:"varint,5,opt,name=charging,proto3" json:"charging,omitempty"`
	ThermalThrottled   bool                   `protobuf:"varint,6,opt,name=thermal_throttled,json=thermalThrottled,proto3" json:"thermal_throttled,omitempty"`
	TemperatureCelsius float64                `protobuf:"fixed64,7,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DynamicMetrics) Reset() {
	*x = DynamicMetrics{}
	mi := &file_distri_v1_capability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMetrics) ProtoMessage() {}

func (x *DynamicMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_capability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMetrics.ProtoReflect.Descriptor instead.
func (*DynamicMetrics) Descriptor() ([]byte, []int) {
	return file_distri_v1_capability_proto_rawDescGZIP(), []int{6}
}

func (x *DynamicMetrics) GetCpuUtilizationPct() float64 {
	if x != nil {
		return x.CpuUtilizationPct
	}
	return 0
}

func (x *DynamicMetrics) GetGpuUtilizationPct() float64 {
	if x != nil {
		return x.GpuUtilizationPct
	}
	return 0
}

func (x *DynamicMetrics) GetMemoryUsedPct() float64 {
	if x != nil {
		return x.MemoryUsedPct
	}
	return 0
}

func (x *DynamicMetrics) GetBatteryPct() float64 {
	if x != nil {
		return x.BatteryPct
	}
	return 0
}

func (x *DynamicMetrics) GetCharging() bool {
	if x != nil {
		return x.Charging
	}
	return false
}

func (x *DynamicMetrics) GetThermalThrottled() bool {
	if x != nil {
		return x.ThermalThrottled
	}
	return false
}

func (x *DynamicMetrics) GetTemperatureCelsius() float64 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

type UserPolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxCpuCores      uint32                 `protobuf:"varint,1,opt,name=max_cpu_cores,json=maxCpuCores,proto3" json:"max_cpu_cores,omitempty"`      // 0 = no limit
	MaxRamMb         uint64                 `protobuf:"varint,2,opt,name=max_ram_mb,json=maxRamMb,proto3" json:"max_ram_mb,omitempty"`               // 0 = no limit
	MaxGpuVramMb     uint64                 `protobuf:"varint,3,opt,name=max_gpu_vram_mb,json=maxGpuVramMb,proto3" json:"max_gpu_vram_mb,omitempty"` // 0 = no limit
	Intensity        float64                `protobuf:"fixed64,4,opt,name=intensity,proto3" json:"intensity,omitempty"`                              // 0.0 - 1.0, fraction of compute to contribute
	OnlyWhenIdle     bool                   `protobuf:"varint,5,opt,name=only_when_idle,json=onlyWhenIdle,proto3" json:"only_when_idle,omitempty"`
	OnlyWhenCharging bool                   `protobuf:"varint,6,opt,name=only_when_charging,json=onlyWhenCharging,proto3" json:"only_when_charging,omitempty"`
	OnlyOnWifi       bool                   `protobuf:"varint,7,opt,name=only_on_wifi,json=onlyOnWifi,proto3" json:"only_on_wifi,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserPolicy) Reset() {
	*x = UserPolicy{}
	mi := &file_distri_v1_capability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPolicy) ProtoMessage() {}

func (x *UserPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_capability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPolicy.ProtoReflect.Descriptor instead.
func (*UserPolicy) Descriptor() ([]byte, []int) {
	return file_distri_v1_capability_proto_rawDescGZIP(), []int{7}
}

func (x *UserPolicy) GetMaxCpuCores() uint32 {
	if x != nil {
		return x.MaxCpuCores
	}
	return 0
}

func (x *UserPolicy) GetMaxRamMb() uint64 {
	if x != nil {
		return x.MaxRamMb
	}
	return 0
}

func (x *UserPolicy) GetMaxGpuVramMb() uint64 {
	if x != nil {
		return x.MaxGpuVramMb
	}
	return 0
}

func (x *UserPolicy) GetIntensity() float64 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

func (x *UserPolicy) GetOnlyWhenIdle() bool {
	if x != nil {
		return x.OnlyWhenIdle
	}
	return false
}

func (x *UserPolicy) GetOnlyWhenCharging() bool {
	if x != nil {
		return x.OnlyWhenCharging
	}
	return false
}

func (x *UserPolicy) GetOnlyOnWifi() bool {
	if x != nil {
		return x.OnlyOnWifi
	}
	return false
}

var File_distri_v1_capability_proto protoreflect.FileDescriptor

const file_distri_v1_capability_proto_rawDesc = "" +
	"\n" +
	"\x1adistri/v1/capability.proto\x12\tdistri.v1\"\xf8\x02\n" +
	"\x10CapabilityReport\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x126\n" +
	"\acompute\x18\x06 \x01(\v2\x1c.distri.v1.ComputeCapabilityR\acompute\x126\n" +
	"\anetwork\x18\a \x01(\v2\x1c.distri.v1.NetworkCapabilityR\anetwork\x123\n" +
	"\adynamic\x18\b \x01(\v2\x19.distri.v1.DynamicMetricsR\adynamic\x126\n" +
	"\vuser_policy\x18\t \x01(\v2\x15.distri.v1.UserPolicyR\n" +
	"userPolicy\"\x8e\x01\n" +
	"\x11ComputeCapability\x12$\n" +
	"\x03cpu\x18\x01 \x01(\v2\x12.distri.v1.CPUInfoR\x03cpu\x12$\n" +
	"\x03gpu\x18\x02 \x01(\v2\x12.distri.v1.GPUInfoR\x03gpu\x12-\n" +
	"\x06memory\x18\x03 \x01(\v2\x15.distri.v1.MemoryInfoR\x06memory\"\xde\x01\n" +
	"\aCPUInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12%\n" +
	"\x0ecores_physical\x18\x02 \x01(\rR\rcoresPhysical\x12#\n" +
	"\rcores_logical\x18\x03 \x01(\rR\fcoresLogical\x12#\n" +
	"\rfrequency_mhz\x18\x04 \x01(\rR\ffrequencyMhz\x12!\n" +
	"\fisa_features\x18\x05 \x03(\tR\visaFeatures\x12)\n" +
	"\x10benchmark_gflops\x18\x06 \x01(\x01R\x0fbenchmarkGflops\"\xb8\x02\n" +
	"\aGPUInfo\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x17\n" +
	"\avram_mb\x18\x03 \x01(\x04R\x06vramMb\x12#\n" +
	"\rcompute_units\x18\x04 \x01(\rR\fcomputeUnits\x12#\n" +
	"\rfrequency_mhz\x18\x05 \x01(\rR\ffrequencyMhz\x12%\n" +
	"\x0eopencl_version\x18\x06 \x01(\tR\ropenclVersion\x12,\n" +
	"\x12opencl_device_name\x18\a \x01(\tR\x10openclDeviceName\x12)\n" +
	"\x10benchmark_gflops\x18\b \x01(\x01R\x0fbenchmarkGflops\x12\x1c\n" +
	"\tavailable\x18\t \x01(\bR\tavailable\"~\n" +
	"\n" +
	"MemoryInfo\x12 \n" +
	"\ftotal_ram_mb\x18\x01 \x01(\x04R\n" +
	"totalRamMb\x12(\n" +
	"\x10available_ram_mb\x18\x02 \x01(\x04R\x0eavailableRamMb\x12$\n" +
	"\x0ebandwidth_gb_s\x18\x03 \x01(\x01R\fbandwidthGbS\"\x9e\x01\n" +
	"\x11NetworkCapability\x12%\n" +
	"\x0einterface_type\x18\x01 \x01(\tR\rinterfaceType\x12%\n" +
	"\x0ebandwidth_mbps\x18\x02 \x01(\rR\rbandwidthMbps\x12;\n" +
	"\x1alatency_ms_to_orchestrator\x18\x03 \x01(\x01R\x17latencyMsToOrchestrator\"\xb3\x02\n" +
	"\x0eDynamicMetrics\x12.\n" +
	"\x13cpu_utilization_pct\x18\x01 \x01(\x01R\x11cpuUtilizationPct\x12.\n" +
	"\x13gpu_utilization_pct\x18\x02 \x01(\x01R\x11gpuUtilizationPct\x12&\n" +
	"\x0fmemory_used_pct\x18\x03 \x01(\x01R\rmemoryUsedPct\x12\x1f\n" +
	"\vbattery_pct\x18\x04 \x01(\x01R\n" +
	"batteryPct\x12\x1a\n" +
	"\bcharging\x18\x05 \x01(\bR\bcharging\x12+\n" +
	"\x11thermal_throttled\x18\x06 \x01(\bR\x10thermalThrottled\x12/\n" +
	"\x13temperature_celsius\x18\a \x01(\x01R\x12temperatureCelsius\"\x89\x02\n" +
	"\n" +
	"UserPolicy\x12\"\n" +
	"\rmax_cpu_cores\x18\x01 \x01(\rR\vmaxCpuCores\x12\x1c\n" +
	"\n" +
	"max_ram_mb\x18\x02 \x01(\x04R\bmaxRamMb\x12%\n" +
	"\x0fmax_gpu_vram_mb\x18\x03 \x01(\x04R\fmaxGpuVramMb\x12\x1c\n" +
	"\tintensity\x18\x04 \x01(\x01R\tintensity\x12$\n" +
	"\x0eonly_when_idle\x18\x05 \x01(\bR\fonlyWhenIdle\x12,\n" +
	"\x12only_when_charging\x18\x06 \x01(\bR\x10onlyWhenCharging\x12 \n" +
	"\fonly_on_wifi\x18\a \x01(\bR\n" +
	"onlyOnWifiB6Z4github.com/distribox/pkg/protocol/distri/v1;distriv1b\x06proto3"

var (
	file_distri_v1_capability_proto_rawDescOnce sync.Once
	file_distri_v1_capability_proto_rawDescData []byte
)

func file_distri_v1_capability_proto_rawDescGZIP() []byte {
	file_distri_v1_capability_proto_rawDescOnce.Do(func() {
		file_distri_v1_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distri_v1_capability_proto_rawDesc), len(file_distri_v1_capability_proto_rawDesc)))
	})
	return file_distri_v1_capability_proto_rawDescData
}

var file_distri_v1_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_distri_v1_capability_proto_goTypes = []any{
	(*CapabilityReport)(nil),  // 0: distri.v1.CapabilityReport
	(*ComputeCapability)(nil), // 1: distri.v1.ComputeCapability
	(*CPUInfo)(nil),           // 2: distri.v1.CPUInfo
	(*GPUInfo)(nil),           // 3: distri.v1.GPUInfo
	(*MemoryInfo)(nil),        // 4: distri.v1.MemoryInfo
	(*NetworkCapability)(nil), // 5: distri.v1.NetworkCapability
	(*DynamicMetrics)(nil),    // 6: distri.v1.DynamicMetrics
	(*UserPolicy)(nil),        // 7: distri.v1.UserPolicy
}
var file_distri_v1_capability_proto_depIdxs = []int32{
	1, // 0: distri.v1.CapabilityReport.compute:type_name -> distri.v1.ComputeCapability
	5, // 1: distri.v1.CapabilityReport.network:type_name -> distri.v1.NetworkCapability
	6, // 2: distri.v1.CapabilityReport.dynamic:type_name -> distri.v1.DynamicMetrics
	7, // 3: distri.v1.CapabilityReport.user_policy:type_name -> distri.v1.UserPolicy
	2, // 4: distri.v1.ComputeCapability.cpu:type_name -> distri.v1.CPUInfo
	3, // 5: distri.v1.ComputeCapability.gpu:type_name -> distri.v1.GPUInfo
	4, // 6: distri.v1.ComputeCapability.memory:type_name -> distri.v1.MemoryInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_distri_v1_capability_proto_init() }
func file_distri_v1_capability_proto_init() {
	if File_distri_v1_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distri_v1_capability_proto_rawDesc), len(file_distri_v1_capability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_distri_v1_capability_proto_goTypes,
		DependencyIndexes: file_distri_v1_capability_proto_depIdxs,
		MessageInfos:      file_distri_v1_capability_proto_msgTypes,
	}.Build()
	File_distri_v1_capability_proto = out.File
	file_distri_v1_capability_proto_goTypes = nil
	file_distri_v1_capability_proto_depIdxs = nil
}
