// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: distri/v1/compute.proto

package distriv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BufferType int32

const (
	BufferType_BUFFER_TYPE_UNSPECIFIED BufferType = 0
	BufferType_BUFFER_TYPE_READ_ONLY   BufferType = 1 // Model weights — replicated to all workers
	BufferType_BUFFER_TYPE_READ_WRITE  BufferType = 2 // Activations — partitioned across workers
	BufferType_BUFFER_TYPE_TEMPORARY   BufferType = 3 // Small, frequent changes — sent inline
)

// Enum value maps for BufferType.
var (
	BufferType_name = map[int32]string{
		0: "BUFFER_TYPE_UNSPECIFIED",
		1: "BUFFER_TYPE_READ_ONLY",
		2: "BUFFER_TYPE_READ_WRITE",
		3: "BUFFER_TYPE_TEMPORARY",
	}
	BufferType_value = map[string]int32{
		"BUFFER_TYPE_UNSPECIFIED": 0,
		"BUFFER_TYPE_READ_ONLY":   1,
		"BUFFER_TYPE_READ_WRITE":  2,
		"BUFFER_TYPE_TEMPORARY":   3,
	}
)

func (x BufferType) Enum() *BufferType {
	p := new(BufferType)
	*p = x
	return p
}

func (x BufferType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BufferType) Descriptor() protoreflect.EnumDescriptor {
	return file_distri_v1_compute_proto_enumTypes[0].Descriptor()
}

func (BufferType) Type() protoreflect.EnumType {
	return &file_distri_v1_compute_proto_enumTypes[0]
}

func (x BufferType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BufferType.Descriptor instead.
func (BufferType) EnumDescriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{0}
}

// A compute task representing an NDRange kernel execution
type ComputeTask struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	KernelId   string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`
	KernelName string                 `protobuf:"bytes,2,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
	ProgramId  string                 `protobuf:"bytes,3,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	// NDRange specification for this sub-task
	WorkDim          uint32   `protobuf:"varint,4,opt,name=work_dim,json=workDim,proto3" json:"work_dim,omitempty"`
	GlobalWorkSize   []uint64 `protobuf:"varint,5,rep,packed,name=global_work_size,json=globalWorkSize,proto3" json:"global_work_size,omitempty"`       // This worker's portion
	GlobalWorkOffset []uint64 `protobuf:"varint,6,rep,packed,name=global_work_offset,json=globalWorkOffset,proto3" json:"global_work_offset,omitempty"` // Offset in the global space
	LocalWorkSize    []uint64 `protobuf:"varint,7,rep,packed,name=local_work_size,json=localWorkSize,proto3" json:"local_work_size,omitempty"`
	// Kernel arguments
	Args          []*KernelArg `protobuf:"bytes,8,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeTask) Reset() {
	*x = ComputeTask{}
	mi := &file_distri_v1_compute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeTask) ProtoMessage() {}

func (x *ComputeTask) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeTask.ProtoReflect.Descriptor instead.
func (*ComputeTask) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeTask) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *ComputeTask) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

func (x *ComputeTask) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *ComputeTask) GetWorkDim() uint32 {
	if x != nil {
		return x.WorkDim
	}
	return 0
}

func (x *ComputeTask) GetGlobalWorkSize() []uint64 {
	if x != nil {
		return x.GlobalWorkSize
	}
	return nil
}

func (x *ComputeTask) GetGlobalWorkOffset() []uint64 {
	if x != nil {
		return x.GlobalWorkOffset
	}
	return nil
}

func (x *ComputeTask) GetLocalWorkSize() []uint64 {
	if x != nil {
		return x.LocalWorkSize
	}
	return nil
}

func (x *ComputeTask) GetArgs() []*KernelArg {
	if x != nil {
		return x.Args
	}
	return nil
}

// A kernel argument (maps to clSetKernelArg)
type KernelArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*KernelArg_Buffer
	//	*KernelArg_Scalar
	Value         isKernelArg_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelArg) Reset() {
	*x = KernelArg{}
	mi := &file_distri_v1_compute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelArg) ProtoMessage() {}

func (x *KernelArg) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelArg.ProtoReflect.Descriptor instead.
func (*KernelArg) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{1}
}

func (x *KernelArg) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *KernelArg) GetValue() isKernelArg_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KernelArg) GetBuffer() *BufferArg {
	if x != nil {
		if x, ok := x.Value.(*KernelArg_Buffer); ok {
			return x.Buffer
		}
	}
	return nil
}

func (x *KernelArg) GetScalar() *ScalarArg {
	if x != nil {
		if x, ok := x.Value.(*KernelArg_Scalar); ok {
			return x.Scalar
		}
	}
	return nil
}

type isKernelArg_Value interface {
	isKernelArg_Value()
}

type KernelArg_Buffer struct {
	Buffer *BufferArg `protobuf:"bytes,2,opt,name=buffer,proto3,oneof"`
}

type KernelArg_Scalar struct {
	Scalar *ScalarArg `protobuf:"bytes,3,opt,name=scalar,proto3,oneof"`
}

func (*KernelArg_Buffer) isKernelArg_Value() {}

func (*KernelArg_Scalar) isKernelArg_Value() {}

type BufferArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BufferId      string                 `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"` // cl_mem_flags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferArg) Reset() {
	*x = BufferArg{}
	mi := &file_distri_v1_compute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferArg) ProtoMessage() {}

func (x *BufferArg) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferArg.ProtoReflect.Descriptor instead.
func (*BufferArg) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{2}
}

func (x *BufferArg) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *BufferArg) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BufferArg) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BufferArg) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type ScalarArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                             // Raw bytes of the scalar value
	SizeBytes     uint32                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // sizeof(arg)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarArg) Reset() {
	*x = ScalarArg{}
	mi := &file_distri_v1_compute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarArg) ProtoMessage() {}

func (x *ScalarArg) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarArg.ProtoReflect.Descriptor instead.
func (*ScalarArg) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{3}
}

func (x *ScalarArg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScalarArg) GetSizeBytes() uint32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Describe a region within a buffer (for partial results)
type BufferRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BufferId      string                 `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	OffsetBytes   uint64                 `protobuf:"varint,2,opt,name=offset_bytes,json=offsetBytes,proto3" json:"offset_bytes,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // Inline data for returning output buffers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferRegion) Reset() {
	*x = BufferRegion{}
	mi := &file_distri_v1_compute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferRegion) ProtoMessage() {}

func (x *BufferRegion) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferRegion.ProtoReflect.Descriptor instead.
func (*BufferRegion) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{4}
}

func (x *BufferRegion) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *BufferRegion) GetOffsetBytes() uint64 {
	if x != nil {
		return x.OffsetBytes
	}
	return 0
}

func (x *BufferRegion) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BufferRegion) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Create/register a buffer on a worker
type BufferCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BufferId      string                 `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Flags         uint32                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"` // cl_mem_flags: READ_ONLY, WRITE_ONLY, READ_WRITE
	BufferType    BufferType             `protobuf:"varint,4,opt,name=buffer_type,json=bufferType,proto3,enum=distri.v1.BufferType" json:"buffer_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferCreateRequest) Reset() {
	*x = BufferCreateRequest{}
	mi := &file_distri_v1_compute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferCreateRequest) ProtoMessage() {}

func (x *BufferCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferCreateRequest.ProtoReflect.Descriptor instead.
func (*BufferCreateRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{5}
}

func (x *BufferCreateRequest) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *BufferCreateRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BufferCreateRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *BufferCreateRequest) GetBufferType() BufferType {
	if x != nil {
		return x.BufferType
	}
	return BufferType_BUFFER_TYPE_UNSPECIFIED
}

type ReadBufferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BufferId      string                 `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	OffsetBytes   uint64                 `protobuf:"varint,2,opt,name=offset_bytes,json=offsetBytes,proto3" json:"offset_bytes,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBufferRequest) Reset() {
	*x = ReadBufferRequest{}
	mi := &file_distri_v1_compute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBufferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBufferRequest) ProtoMessage() {}

func (x *ReadBufferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBufferRequest.ProtoReflect.Descriptor instead.
func (*ReadBufferRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{6}
}

func (x *ReadBufferRequest) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *ReadBufferRequest) GetOffsetBytes() uint64 {
	if x != nil {
		return x.OffsetBytes
	}
	return 0
}

func (x *ReadBufferRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ReadBufferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	BytesRead     uint64                 `protobuf:"varint,2,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBufferResponse) Reset() {
	*x = ReadBufferResponse{}
	mi := &file_distri_v1_compute_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBufferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBufferResponse) ProtoMessage() {}

func (x *ReadBufferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBufferResponse.ProtoReflect.Descriptor instead.
func (*ReadBufferResponse) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{7}
}

func (x *ReadBufferResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadBufferResponse) GetBytesRead() uint64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

type WriteBufferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BufferId      string                 `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	OffsetBytes   uint64                 `protobuf:"varint,2,opt,name=offset_bytes,json=offsetBytes,proto3" json:"offset_bytes,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBufferRequest) Reset() {
	*x = WriteBufferRequest{}
	mi := &file_distri_v1_compute_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBufferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBufferRequest) ProtoMessage() {}

func (x *WriteBufferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBufferRequest.ProtoReflect.Descriptor instead.
func (*WriteBufferRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{8}
}

func (x *WriteBufferRequest) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *WriteBufferRequest) GetOffsetBytes() uint64 {
	if x != nil {
		return x.OffsetBytes
	}
	return 0
}

func (x *WriteBufferRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CopyBufferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcBufferId   string                 `protobuf:"bytes,1,opt,name=src_buffer_id,json=srcBufferId,proto3" json:"src_buffer_id,omitempty"`
	DstBufferId   string                 `protobuf:"bytes,2,opt,name=dst_buffer_id,json=dstBufferId,proto3" json:"dst_buffer_id,omitempty"`
	SrcOffset     uint64                 `protobuf:"varint,3,opt,name=src_offset,json=srcOffset,proto3" json:"src_offset,omitempty"`
	DstOffset     uint64                 `protobuf:"varint,4,opt,name=dst_offset,json=dstOffset,proto3" json:"dst_offset,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyBufferRequest) Reset() {
	*x = CopyBufferRequest{}
	mi := &file_distri_v1_compute_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyBufferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyBufferRequest) ProtoMessage() {}

func (x *CopyBufferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyBufferRequest.ProtoReflect.Descriptor instead.
func (*CopyBufferRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{9}
}

func (x *CopyBufferRequest) GetSrcBufferId() string {
	if x != nil {
		return x.SrcBufferId
	}
	return ""
}

func (x *CopyBufferRequest) GetDstBufferId() string {
	if x != nil {
		return x.DstBufferId
	}
	return ""
}

func (x *CopyBufferRequest) GetSrcOffset() uint64 {
	if x != nil {
		return x.SrcOffset
	}
	return 0
}

func (x *CopyBufferRequest) GetDstOffset() uint64 {
	if x != nil {
		return x.DstOffset
	}
	return 0
}

func (x *CopyBufferRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type FillBufferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BufferId      string                 `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	Pattern       []byte                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	OffsetBytes   uint64                 `protobuf:"varint,3,opt,name=offset_bytes,json=offsetBytes,proto3" json:"offset_bytes,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillBufferRequest) Reset() {
	*x = FillBufferRequest{}
	mi := &file_distri_v1_compute_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillBufferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillBufferRequest) ProtoMessage() {}

func (x *FillBufferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillBufferRequest.ProtoReflect.Descriptor instead.
func (*FillBufferRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{10}
}

func (x *FillBufferRequest) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *FillBufferRequest) GetPattern() []byte {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *FillBufferRequest) GetOffsetBytes() uint64 {
	if x != nil {
		return x.OffsetBytes
	}
	return 0
}

func (x *FillBufferRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type CreateProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     string                 `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	Source        []byte                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`   // OpenCL C source code
	Options       string                 `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"` // Compile options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProgramRequest) Reset() {
	*x = CreateProgramRequest{}
	mi := &file_distri_v1_compute_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProgramRequest) ProtoMessage() {}

func (x *CreateProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProgramRequest.ProtoReflect.Descriptor instead.
func (*CreateProgramRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{11}
}

func (x *CreateProgramRequest) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *CreateProgramRequest) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CreateProgramRequest) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

type BuildProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     string                 `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	Options       string                 `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildProgramRequest) Reset() {
	*x = BuildProgramRequest{}
	mi := &file_distri_v1_compute_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildProgramRequest) ProtoMessage() {}

func (x *BuildProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildProgramRequest.ProtoReflect.Descriptor instead.
func (*BuildProgramRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{12}
}

func (x *BuildProgramRequest) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *BuildProgramRequest) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

type BuildProgramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BuildLog      string                 `protobuf:"bytes,2,opt,name=build_log,json=buildLog,proto3" json:"build_log,omitempty"`
	Binaries      []*KernelBinary        `protobuf:"bytes,3,rep,name=binaries,proto3" json:"binaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildProgramResponse) Reset() {
	*x = BuildProgramResponse{}
	mi := &file_distri_v1_compute_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildProgramResponse) ProtoMessage() {}

func (x *BuildProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildProgramResponse.ProtoReflect.Descriptor instead.
func (*BuildProgramResponse) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{13}
}

func (x *BuildProgramResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildProgramResponse) GetBuildLog() string {
	if x != nil {
		return x.BuildLog
	}
	return ""
}

func (x *BuildProgramResponse) GetBinaries() []*KernelBinary {
	if x != nil {
		return x.Binaries
	}
	return nil
}

type KernelBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelName    string                 `protobuf:"bytes,1,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
	Binary        []byte                 `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"` // Platform-specific compiled binary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelBinary) Reset() {
	*x = KernelBinary{}
	mi := &file_distri_v1_compute_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelBinary) ProtoMessage() {}

func (x *KernelBinary) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelBinary.ProtoReflect.Descriptor instead.
func (*KernelBinary) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{14}
}

func (x *KernelBinary) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

func (x *KernelBinary) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

type CreateKernelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelId      string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`
	KernelName    string                 `protobuf:"bytes,2,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
	ProgramId     string                 `protobuf:"bytes,3,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKernelRequest) Reset() {
	*x = CreateKernelRequest{}
	mi := &file_distri_v1_compute_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKernelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKernelRequest) ProtoMessage() {}

func (x *CreateKernelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_compute_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKernelRequest.ProtoReflect.Descriptor instead.
func (*CreateKernelRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_compute_proto_rawDescGZIP(), []int{15}
}

func (x *CreateKernelRequest) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *CreateKernelRequest) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

func (x *CreateKernelRequest) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

var File_distri_v1_compute_proto protoreflect.FileDescriptor

const file_distri_v1_compute_proto_rawDesc = "" +
	"\n" +
	"\x17distri/v1/compute.proto\x12\tdistri.v1\"\xaf\x02\n" +
	"\vComputeTask\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x1f\n" +
	"\vkernel_name\x18\x02 \x01(\tR\n" +
	"kernelName\x12\x1d\n" +
	"\n" +
	"program_id\x18\x03 \x01(\tR\tprogramId\x12\x19\n" +
	"\bwork_dim\x18\x04 \x01(\rR\aworkDim\x12(\n" +
	"\x10global_work_size\x18\x05 \x03(\x04R\x0eglobalWorkSize\x12,\n" +
	"\x12global_work_offset\x18\x06 \x03(\x04R\x10globalWorkOffset\x12&\n" +
	"\x0flocal_work_size\x18\a \x03(\x04R\rlocalWorkSize\x12(\n" +
	"\x04args\x18\b \x03(\v2\x14.distri.v1.KernelArgR\x04args\"\x8a\x01\n" +
	"\tKernelArg\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12.\n" +
	"\x06buffer\x18\x02 \x01(\v2\x14.distri.v1.BufferArgH\x00R\x06buffer\x12.\n" +
	"\x06scalar\x18\x03 \x01(\v2\x14.distri.v1.ScalarArgH\x00R\x06scalarB\a\n" +
	"\x05value\"u\n" +
	"\tBufferArg\x12\x1b\n" +
	"\tbuffer_id\x18\x01 \x01(\tR\bbufferId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\">\n" +
	"\tScalarArg\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\rR\tsizeBytes\"\x81\x01\n" +
	"\fBufferRegion\x12\x1b\n" +
	"\tbuffer_id\x18\x01 \x01(\tR\bbufferId\x12!\n" +
	"\foffset_bytes\x18\x02 \x01(\x04R\voffsetBytes\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x9f\x01\n" +
	"\x13BufferCreateRequest\x12\x1b\n" +
	"\tbuffer_id\x18\x01 \x01(\tR\bbufferId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\x126\n" +
	"\vbuffer_type\x18\x04 \x01(\x0e2\x15.distri.v1.BufferTypeR\n" +
	"bufferType\"r\n" +
	"\x11ReadBufferRequest\x12\x1b\n" +
	"\tbuffer_id\x18\x01 \x01(\tR\bbufferId\x12!\n" +
	"\foffset_bytes\x18\x02 \x01(\x04R\voffsetBytes\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\"G\n" +
	"\x12ReadBufferResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\x02 \x01(\x04R\tbytesRead\"h\n" +
	"\x12WriteBufferRequest\x12\x1b\n" +
	"\tbuffer_id\x18\x01 \x01(\tR\bbufferId\x12!\n" +
	"\foffset_bytes\x18\x02 \x01(\x04R\voffsetBytes\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xb8\x01\n" +
	"\x11CopyBufferRequest\x12\"\n" +
	"\rsrc_buffer_id\x18\x01 \x01(\tR\vsrcBufferId\x12\"\n" +
	"\rdst_buffer_id\x18\x02 \x01(\tR\vdstBufferId\x12\x1d\n" +
	"\n" +
	"src_offset\x18\x03 \x01(\x04R\tsrcOffset\x12\x1d\n" +
	"\n" +
	"dst_offset\x18\x04 \x01(\x04R\tdstOffset\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\"\x8c\x01\n" +
	"\x11FillBufferRequest\x12\x1b\n" +
	"\tbuffer_id\x18\x01 \x01(\tR\bbufferId\x12\x18\n" +
	"\apattern\x18\x02 \x01(\fR\apattern\x12!\n" +
	"\foffset_bytes\x18\x03 \x01(\x04R\voffsetBytes\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\"g\n" +
	"\x14CreateProgramRequest\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\tR\tprogramId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\fR\x06source\x12\x18\n" +
	"\aoptions\x18\x03 \x01(\tR\aoptions\"N\n" +
	"\x13BuildProgramRequest\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\tR\tprogramId\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\tR\aoptions\"\x82\x01\n" +
	"\x14BuildProgramResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tbuild_log\x18\x02 \x01(\tR\bbuildLog\x123\n" +
	"\bbinaries\x18\x03 \x03(\v2\x17.distri.v1.KernelBinaryR\bbinaries\"G\n" +
	"\fKernelBinary\x12\x1f\n" +
	"\vkernel_name\x18\x01 \x01(\tR\n" +
	"kernelName\x12\x16\n" +
	"\x06binary\x18\x02 \x01(\fR\x06binary\"r\n" +
	"\x13CreateKernelRequest\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x1f\n" +
	"\vkernel_name\x18\x02 \x01(\tR\n" +
	"kernelName\x12\x1d\n" +
	"\n" +
	"program_id\x18\x03 \x01(\tR\tprogramId*{\n" +
	"\n" +
	"BufferType\x12\x1b\n" +
	"\x17BUFFER_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BUFFER_TYPE_READ_ONLY\x10\x01\x12\x1a\n" +
	"\x16BUFFER_TYPE_READ_WRITE\x10\x02\x12\x19\n" +
	"\x15BUFFER_TYPE_TEMPORARY\x10\x03B6Z4github.com/distribox/pkg/protocol/distri/v1;distriv1b\x06proto3"

var (
	file_distri_v1_compute_proto_rawDescOnce sync.Once
	file_distri_v1_compute_proto_rawDescData []byte
)

func file_distri_v1_compute_proto_rawDescGZIP() []byte {
	file_distri_v1_compute_proto_rawDescOnce.Do(func() {
		file_distri_v1_compute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distri_v1_compute_proto_rawDesc), len(file_distri_v1_compute_proto_rawDesc)))
	})
	return file_distri_v1_compute_proto_rawDescData
}

var file_distri_v1_compute_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_distri_v1_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_distri_v1_compute_proto_goTypes = []any{
	(BufferType)(0),              // 0: distri.v1.BufferType
	(*ComputeTask)(nil),          // 1: distri.v1.ComputeTask
	(*KernelArg)(nil),            // 2: distri.v1.KernelArg
	(*BufferArg)(nil),            // 3: distri.v1.BufferArg
	(*ScalarArg)(nil),            // 4: distri.v1.ScalarArg
	(*BufferRegion)(nil),         // 5: distri.v1.BufferRegion
	(*BufferCreateRequest)(nil),  // 6: distri.v1.BufferCreateRequest
	(*ReadBufferRequest)(nil),    // 7: distri.v1.ReadBufferRequest
	(*ReadBufferResponse)(nil),   // 8: distri.v1.ReadBufferResponse
	(*WriteBufferRequest)(nil),   // 9: distri.v1.WriteBufferRequest
	(*CopyBufferRequest)(nil),    // 10: distri.v1.CopyBufferRequest
	(*FillBufferRequest)(nil),    // 11: distri.v1.FillBufferRequest
	(*CreateProgramRequest)(nil), // 12: distri.v1.CreateProgramRequest
	(*BuildProgramRequest)(nil),  // 13: distri.v1.BuildProgramRequest
	(*BuildProgramResponse)(nil), // 14: distri.v1.BuildProgramResponse
	(*KernelBinary)(nil),         // 15: distri.v1.KernelBinary
	(*CreateKernelRequest)(nil),  // 16: distri.v1.CreateKernelRequest
}
var file_distri_v1_compute_proto_depIdxs = []int32{
	2,  // 0: distri.v1.ComputeTask.args:type_name -> distri.v1.KernelArg
	3,  // 1: distri.v1.KernelArg.buffer:type_name -> distri.v1.BufferArg
	4,  // 2: distri.v1.KernelArg.scalar:type_name -> distri.v1.ScalarArg
	0,  // 3: distri.v1.BufferCreateRequest.buffer_type:type_name -> distri.v1.BufferType
	15, // 4: distri.v1.BuildProgramResponse.binaries:type_name -> distri.v1.KernelBinary
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_distri_v1_compute_proto_init() }
func file_distri_v1_compute_proto_init() {
	if File_distri_v1_compute_proto != nil {
		return
	}
	file_distri_v1_compute_proto_msgTypes[1].OneofWrappers = []any{
		(*KernelArg_Buffer)(nil),
		(*KernelArg_Scalar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distri_v1_compute_proto_rawDesc), len(file_distri_v1_compute_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_distri_v1_compute_proto_goTypes,
		DependencyIndexes: file_distri_v1_compute_proto_depIdxs,
		EnumInfos:         file_distri_v1_compute_proto_enumTypes,
		MessageInfos:      file_distri_v1_compute_proto_msgTypes,
	}.Build()
	File_distri_v1_compute_proto = out.File
	file_distri_v1_compute_proto_goTypes = nil
	file_distri_v1_compute_proto_depIdxs = nil
}
