// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.3
// source: distri/v1/control.proto

package distriv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Orchestrator_Register_FullMethodName       = "/distri.v1.Orchestrator/Register"
	Orchestrator_ControlChannel_FullMethodName = "/distri.v1.Orchestrator/ControlChannel"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	// Worker registers with orchestrator, receives worker ID + session token
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Bidirectional stream for ongoing communication:
	// - Capability reports (worker �?orchestrator)
	// - Shard/task assignments (orchestrator �?worker)
	// - Heartbeat pings
	ControlChannel(ctx context.Context, opts ...grpc.CallOption) (Orchestrator_ControlChannelClient, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Orchestrator_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ControlChannel(ctx context.Context, opts ...grpc.CallOption) (Orchestrator_ControlChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[0], Orchestrator_ControlChannel_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorControlChannelClient{stream}
	return x, nil
}

type Orchestrator_ControlChannelClient interface {
	Send(*WorkerMessage) error
	Recv() (*OrchestratorMessage, error)
	grpc.ClientStream
}

type orchestratorControlChannelClient struct {
	grpc.ClientStream
}

func (x *orchestratorControlChannelClient) Send(m *WorkerMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orchestratorControlChannelClient) Recv() (*OrchestratorMessage, error) {
	m := new(OrchestratorMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility
type OrchestratorServer interface {
	// Worker registers with orchestrator, receives worker ID + session token
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Bidirectional stream for ongoing communication:
	// - Capability reports (worker �?orchestrator)
	// - Shard/task assignments (orchestrator �?worker)
	// - Heartbeat pings
	ControlChannel(Orchestrator_ControlChannelServer) error
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServer struct {
}

func (UnimplementedOrchestratorServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedOrchestratorServer) ControlChannel(Orchestrator_ControlChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method ControlChannel not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ControlChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrchestratorServer).ControlChannel(&orchestratorControlChannelServer{stream})
}

type Orchestrator_ControlChannelServer interface {
	Send(*OrchestratorMessage) error
	Recv() (*WorkerMessage, error)
	grpc.ServerStream
}

type orchestratorControlChannelServer struct {
	grpc.ServerStream
}

func (x *orchestratorControlChannelServer) Send(m *OrchestratorMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orchestratorControlChannelServer) Recv() (*WorkerMessage, error) {
	m := new(WorkerMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distri.v1.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Orchestrator_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlChannel",
			Handler:       _Orchestrator_ControlChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "distri/v1/control.proto",
}
