// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: distri/v1/control.proto

package distriv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 1
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETE    TaskStatus = 3
	TaskStatus_TASK_STATUS_ERROR       TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_QUEUED",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_COMPLETE",
		4: "TASK_STATUS_ERROR",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_QUEUED":      1,
		"TASK_STATUS_RUNNING":     2,
		"TASK_STATUS_COMPLETE":    3,
		"TASK_STATUS_ERROR":       4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_distri_v1_control_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_distri_v1_control_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{0}
}

type TransferDirection int32

const (
	TransferDirection_TRANSFER_UNSPECIFIED TransferDirection = 0
	TransferDirection_TRANSFER_TO_WORKER   TransferDirection = 1
	TransferDirection_TRANSFER_FROM_WORKER TransferDirection = 2
)

// Enum value maps for TransferDirection.
var (
	TransferDirection_name = map[int32]string{
		0: "TRANSFER_UNSPECIFIED",
		1: "TRANSFER_TO_WORKER",
		2: "TRANSFER_FROM_WORKER",
	}
	TransferDirection_value = map[string]int32{
		"TRANSFER_UNSPECIFIED": 0,
		"TRANSFER_TO_WORKER":   1,
		"TRANSFER_FROM_WORKER": 2,
	}
)

func (x TransferDirection) Enum() *TransferDirection {
	p := new(TransferDirection)
	*p = x
	return p
}

func (x TransferDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_distri_v1_control_proto_enumTypes[1].Descriptor()
}

func (TransferDirection) Type() protoreflect.EnumType {
	return &file_distri_v1_control_proto_enumTypes[1]
}

func (x TransferDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferDirection.Descriptor instead.
func (TransferDirection) EnumDescriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{1}
}

type RegisterRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Hostname  string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                    // Human-readable device name
	Arch      string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`                            // CPU architecture: amd64, arm64, etc.
	Os        string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`                                // Operating system
	AuthToken string                 `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // Pre-shared cluster token
	// Quick summary for immediate filtering (matches mDNS TXT records)
	TotalRamMb      uint64 `protobuf:"varint,5,opt,name=total_ram_mb,json=totalRamMb,proto3" json:"total_ram_mb,omitempty"`
	HasGpu          bool   `protobuf:"varint,6,opt,name=has_gpu,json=hasGpu,proto3" json:"has_gpu,omitempty"`
	GpuVendor       string `protobuf:"bytes,7,opt,name=gpu_vendor,json=gpuVendor,proto3" json:"gpu_vendor,omitempty"`
	ProtocolVersion string `protobuf:"bytes,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // Expected: "1.0"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_distri_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterRequest) GetTotalRamMb() uint64 {
	if x != nil {
		return x.TotalRamMb
	}
	return 0
}

func (x *RegisterRequest) GetHasGpu() bool {
	if x != nil {
		return x.HasGpu
	}
	return false
}

func (x *RegisterRequest) GetGpuVendor() string {
	if x != nil {
		return x.GpuVendor
	}
	return ""
}

func (x *RegisterRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type RegisterResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WorkerId            string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`             // UUID assigned by orchestrator
	SessionToken        string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // JWT for subsequent requests
	OrchestratorVersion string                 `protobuf:"bytes,3,opt,name=orchestrator_version,json=orchestratorVersion,proto3" json:"orchestrator_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_distri_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterResponse) GetOrchestratorVersion() string {
	if x != nil {
		return x.OrchestratorVersion
	}
	return ""
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_CapabilityUpdate
	//	*WorkerMessage_TaskResult
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_CompileResult
	//	*WorkerMessage_Buffer
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_distri_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetCapabilityUpdate() *CapabilityReport {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_CapabilityUpdate); ok {
			return x.CapabilityUpdate
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetCompileResult() *CompileResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_CompileResult); ok {
			return x.CompileResult
		}
	}
	return nil
}

func (x *WorkerMessage) GetBuffer() *BufferTransfer {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Buffer); ok {
			return x.Buffer
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_CapabilityUpdate struct {
	CapabilityUpdate *CapabilityReport `protobuf:"bytes,1,opt,name=capability_update,json=capabilityUpdate,proto3,oneof"`
}

type WorkerMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,2,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_CompileResult struct {
	CompileResult *CompileResult `protobuf:"bytes,4,opt,name=compile_result,json=compileResult,proto3,oneof"`
}

type WorkerMessage_Buffer struct {
	Buffer *BufferTransfer `protobuf:"bytes,5,opt,name=buffer,proto3,oneof"`
}

func (*WorkerMessage_CapabilityUpdate) isWorkerMessage_Payload() {}

func (*WorkerMessage_TaskResult) isWorkerMessage_Payload() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_CompileResult) isWorkerMessage_Payload() {}

func (*WorkerMessage_Buffer) isWorkerMessage_Payload() {}

type OrchestratorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OrchestratorMessage_Task
	//	*OrchestratorMessage_Compile
	//	*OrchestratorMessage_Buffer
	//	*OrchestratorMessage_HeartbeatAck
	//	*OrchestratorMessage_Shutdown
	Payload       isOrchestratorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorMessage) Reset() {
	*x = OrchestratorMessage{}
	mi := &file_distri_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage) ProtoMessage() {}

func (x *OrchestratorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *OrchestratorMessage) GetPayload() isOrchestratorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OrchestratorMessage) GetTask() *TaskAssignment {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetCompile() *CompileRequest {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_Compile); ok {
			return x.Compile
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetBuffer() *BufferTransfer {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_Buffer); ok {
			return x.Buffer
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isOrchestratorMessage_Payload interface {
	isOrchestratorMessage_Payload()
}

type OrchestratorMessage_Task struct {
	Task *TaskAssignment `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type OrchestratorMessage_Compile struct {
	Compile *CompileRequest `protobuf:"bytes,2,opt,name=compile,proto3,oneof"`
}

type OrchestratorMessage_Buffer struct {
	Buffer *BufferTransfer `protobuf:"bytes,3,opt,name=buffer,proto3,oneof"`
}

type OrchestratorMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,4,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type OrchestratorMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,5,opt,name=shutdown,proto3,oneof"`
}

func (*OrchestratorMessage_Task) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_Compile) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_Buffer) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_HeartbeatAck) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_Shutdown) isOrchestratorMessage_Payload() {}

type Heartbeat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMs  int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	CpuUtilization   float64                `protobuf:"fixed64,2,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`
	GpuUtilization   float64                `protobuf:"fixed64,3,opt,name=gpu_utilization,json=gpuUtilization,proto3" json:"gpu_utilization,omitempty"`
	MemoryUsedPct    float64                `protobuf:"fixed64,4,opt,name=memory_used_pct,json=memoryUsedPct,proto3" json:"memory_used_pct,omitempty"`
	ThermalThrottled bool                   `protobuf:"varint,5,opt,name=thermal_throttled,json=thermalThrottled,proto3" json:"thermal_throttled,omitempty"`
	BatteryPct       float64                `protobuf:"fixed64,6,opt,name=battery_pct,json=batteryPct,proto3" json:"battery_pct,omitempty"`
	Charging         bool                   `protobuf:"varint,7,opt,name=charging,proto3" json:"charging,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_distri_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *Heartbeat) GetCpuUtilization() float64 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

func (x *Heartbeat) GetGpuUtilization() float64 {
	if x != nil {
		return x.GpuUtilization
	}
	return 0
}

func (x *Heartbeat) GetMemoryUsedPct() float64 {
	if x != nil {
		return x.MemoryUsedPct
	}
	return 0
}

func (x *Heartbeat) GetThermalThrottled() bool {
	if x != nil {
		return x.ThermalThrottled
	}
	return false
}

func (x *Heartbeat) GetBatteryPct() float64 {
	if x != nil {
		return x.BatteryPct
	}
	return 0
}

func (x *Heartbeat) GetCharging() bool {
	if x != nil {
		return x.Charging
	}
	return false
}

type HeartbeatAck struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServerTimestampUnixMs int64                  `protobuf:"varint,1,opt,name=server_timestamp_unix_ms,json=serverTimestampUnixMs,proto3" json:"server_timestamp_unix_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_distri_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatAck) GetServerTimestampUnixMs() int64 {
	if x != nil {
		return x.ServerTimestampUnixMs
	}
	return 0
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Graceful      bool                   `protobuf:"varint,2,opt,name=graceful,proto3" json:"graceful,omitempty"` // If true, worker should finish current tasks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_distri_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Shutdown) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type TaskAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CommandQueueId string                 `protobuf:"bytes,2,opt,name=command_queue_id,json=commandQueueId,proto3" json:"command_queue_id,omitempty"` // Which queue this task belongs to
	// NDRange specification for this worker's portion
	Compute *ComputeTask `protobuf:"bytes,3,opt,name=compute,proto3" json:"compute,omitempty"`
	// Buffer references (the worker must already have these buffers)
	InputBufferIds  []string `protobuf:"bytes,4,rep,name=input_buffer_ids,json=inputBufferIds,proto3" json:"input_buffer_ids,omitempty"`
	OutputBufferIds []string `protobuf:"bytes,5,rep,name=output_buffer_ids,json=outputBufferIds,proto3" json:"output_buffer_ids,omitempty"`
	// Event dependencies: complete these local events before starting
	WaitEventIds  []string `protobuf:"bytes,6,rep,name=wait_event_ids,json=waitEventIds,proto3" json:"wait_event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_distri_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetCommandQueueId() string {
	if x != nil {
		return x.CommandQueueId
	}
	return ""
}

func (x *TaskAssignment) GetCompute() *ComputeTask {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *TaskAssignment) GetInputBufferIds() []string {
	if x != nil {
		return x.InputBufferIds
	}
	return nil
}

func (x *TaskAssignment) GetOutputBufferIds() []string {
	if x != nil {
		return x.OutputBufferIds
	}
	return nil
}

func (x *TaskAssignment) GetWaitEventIds() []string {
	if x != nil {
		return x.WaitEventIds
	}
	return nil
}

type TaskResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TaskId       string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status       TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=distri.v1.TaskStatus" json:"status,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// For NDRange results: where to write the partial output
	OutputRegions []*BufferRegion `protobuf:"bytes,4,rep,name=output_regions,json=outputRegions,proto3" json:"output_regions,omitempty"`
	// Timing info
	StartTimeNs   int64 `protobuf:"varint,5,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"`
	EndTimeNs     int64 `protobuf:"varint,6,opt,name=end_time_ns,json=endTimeNs,proto3" json:"end_time_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_distri_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetOutputRegions() []*BufferRegion {
	if x != nil {
		return x.OutputRegions
	}
	return nil
}

func (x *TaskResult) GetStartTimeNs() int64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

func (x *TaskResult) GetEndTimeNs() int64 {
	if x != nil {
		return x.EndTimeNs
	}
	return 0
}

type BufferTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BufferId      string                 `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	Direction     TransferDirection      `protobuf:"varint,2,opt,name=direction,proto3,enum=distri.v1.TransferDirection" json:"direction,omitempty"` // TO_WORKER or FROM_WORKER
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`                                       // cl_mem_flags
	DataPlaneAddr string                 `protobuf:"bytes,5,opt,name=data_plane_addr,json=dataPlaneAddr,proto3" json:"data_plane_addr,omitempty"` // TCP address for data transfer
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                          // Inline data for small/medium buffers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferTransfer) Reset() {
	*x = BufferTransfer{}
	mi := &file_distri_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferTransfer) ProtoMessage() {}

func (x *BufferTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferTransfer.ProtoReflect.Descriptor instead.
func (*BufferTransfer) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *BufferTransfer) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *BufferTransfer) GetDirection() TransferDirection {
	if x != nil {
		return x.Direction
	}
	return TransferDirection_TRANSFER_UNSPECIFIED
}

func (x *BufferTransfer) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BufferTransfer) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *BufferTransfer) GetDataPlaneAddr() string {
	if x != nil {
		return x.DataPlaneAddr
	}
	return ""
}

func (x *BufferTransfer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CompileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramId      string                 `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	KernelSource   string                 `protobuf:"bytes,2,opt,name=kernel_source,json=kernelSource,proto3" json:"kernel_source,omitempty"`
	CompileOptions string                 `protobuf:"bytes,3,opt,name=compile_options,json=compileOptions,proto3" json:"compile_options,omitempty"`
	KernelName     string                 `protobuf:"bytes,4,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"` // Specific kernel to compile
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_distri_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *CompileRequest) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *CompileRequest) GetKernelSource() string {
	if x != nil {
		return x.KernelSource
	}
	return ""
}

func (x *CompileRequest) GetCompileOptions() string {
	if x != nil {
		return x.CompileOptions
	}
	return ""
}

func (x *CompileRequest) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

type CompileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     string                 `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	KernelName    string                 `protobuf:"bytes,2,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	BuildLog      string                 `protobuf:"bytes,4,opt,name=build_log,json=buildLog,proto3" json:"build_log,omitempty"`
	Binary        []byte                 `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"` // Compiled binary for caching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResult) Reset() {
	*x = CompileResult{}
	mi := &file_distri_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResult) ProtoMessage() {}

func (x *CompileResult) ProtoReflect() protoreflect.Message {
	mi := &file_distri_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResult.ProtoReflect.Descriptor instead.
func (*CompileResult) Descriptor() ([]byte, []int) {
	return file_distri_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *CompileResult) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *CompileResult) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

func (x *CompileResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompileResult) GetBuildLog() string {
	if x != nil {
		return x.BuildLog
	}
	return ""
}

func (x *CompileResult) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

var File_distri_v1_control_proto protoreflect.FileDescriptor

const file_distri_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17distri/v1/control.proto\x12\tdistri.v1\x1a\x1adistri/v1/capability.proto\x1a\x17distri/v1/compute.proto\"\xf5\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x04 \x01(\tR\tauthToken\x12 \n" +
	"\ftotal_ram_mb\x18\x05 \x01(\x04R\n" +
	"totalRamMb\x12\x17\n" +
	"\ahas_gpu\x18\x06 \x01(\bR\x06hasGpu\x12\x1d\n" +
	"\n" +
	"gpu_vendor\x18\a \x01(\tR\tgpuVendor\x12)\n" +
	"\x10protocol_version\x18\b \x01(\tR\x0fprotocolVersion\"\x87\x01\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x121\n" +
	"\x14orchestrator_version\x18\x03 \x01(\tR\x13orchestratorVersion\"\xce\x02\n" +
	"\rWorkerMessage\x12J\n" +
	"\x11capability_update\x18\x01 \x01(\v2\x1b.distri.v1.CapabilityReportH\x00R\x10capabilityUpdate\x128\n" +
	"\vtask_result\x18\x02 \x01(\v2\x15.distri.v1.TaskResultH\x00R\n" +
	"taskResult\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.distri.v1.HeartbeatH\x00R\theartbeat\x12A\n" +
	"\x0ecompile_result\x18\x04 \x01(\v2\x18.distri.v1.CompileResultH\x00R\rcompileResult\x123\n" +
	"\x06buffer\x18\x05 \x01(\v2\x19.distri.v1.BufferTransferH\x00R\x06bufferB\t\n" +
	"\apayload\"\xb0\x02\n" +
	"\x13OrchestratorMessage\x12/\n" +
	"\x04task\x18\x01 \x01(\v2\x19.distri.v1.TaskAssignmentH\x00R\x04task\x125\n" +
	"\acompile\x18\x02 \x01(\v2\x19.distri.v1.CompileRequestH\x00R\acompile\x123\n" +
	"\x06buffer\x18\x03 \x01(\v2\x19.distri.v1.BufferTransferH\x00R\x06buffer\x12>\n" +
	"\rheartbeat_ack\x18\x04 \x01(\v2\x17.distri.v1.HeartbeatAckH\x00R\fheartbeatAck\x121\n" +
	"\bshutdown\x18\x05 \x01(\v2\x13.distri.v1.ShutdownH\x00R\bshutdownB\t\n" +
	"\apayload\"\x9b\x02\n" +
	"\tHeartbeat\x12*\n" +
	"\x11timestamp_unix_ms\x18\x01 \x01(\x03R\x0ftimestampUnixMs\x12'\n" +
	"\x0fcpu_utilization\x18\x02 \x01(\x01R\x0ecpuUtilization\x12'\n" +
	"\x0fgpu_utilization\x18\x03 \x01(\x01R\x0egpuUtilization\x12&\n" +
	"\x0fmemory_used_pct\x18\x04 \x01(\x01R\rmemoryUsedPct\x12+\n" +
	"\x11thermal_throttled\x18\x05 \x01(\bR\x10thermalThrottled\x12\x1f\n" +
	"\vbattery_pct\x18\x06 \x01(\x01R\n" +
	"batteryPct\x12\x1a\n" +
	"\bcharging\x18\a \x01(\bR\bcharging\"G\n" +
	"\fHeartbeatAck\x127\n" +
	"\x18server_timestamp_unix_ms\x18\x01 \x01(\x03R\x15serverTimestampUnixMs\">\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x1a\n" +
	"\bgraceful\x18\x02 \x01(\bR\bgraceful\"\x81\x02\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12(\n" +
	"\x10command_queue_id\x18\x02 \x01(\tR\x0ecommandQueueId\x120\n" +
	"\acompute\x18\x03 \x01(\v2\x16.distri.v1.ComputeTaskR\acompute\x12(\n" +
	"\x10input_buffer_ids\x18\x04 \x03(\tR\x0einputBufferIds\x12*\n" +
	"\x11output_buffer_ids\x18\x05 \x03(\tR\x0foutputBufferIds\x12$\n" +
	"\x0ewait_event_ids\x18\x06 \x03(\tR\fwaitEventIds\"\xfd\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.distri.v1.TaskStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12>\n" +
	"\x0eoutput_regions\x18\x04 \x03(\v2\x17.distri.v1.BufferRegionR\routputRegions\x12\"\n" +
	"\rstart_time_ns\x18\x05 \x01(\x03R\vstartTimeNs\x12\x1e\n" +
	"\vend_time_ns\x18\x06 \x01(\x03R\tendTimeNs\"\xda\x01\n" +
	"\x0eBufferTransfer\x12\x1b\n" +
	"\tbuffer_id\x18\x01 \x01(\tR\bbufferId\x12:\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1c.distri.v1.TransferDirectionR\tdirection\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12&\n" +
	"\x0fdata_plane_addr\x18\x05 \x01(\tR\rdataPlaneAddr\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\x9e\x01\n" +
	"\x0eCompileRequest\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\tR\tprogramId\x12#\n" +
	"\rkernel_source\x18\x02 \x01(\tR\fkernelSource\x12'\n" +
	"\x0fcompile_options\x18\x03 \x01(\tR\x0ecompileOptions\x12\x1f\n" +
	"\vkernel_name\x18\x04 \x01(\tR\n" +
	"kernelName\"\x9e\x01\n" +
	"\rCompileResult\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\tR\tprogramId\x12\x1f\n" +
	"\vkernel_name\x18\x02 \x01(\tR\n" +
	"kernelName\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1b\n" +
	"\tbuild_log\x18\x04 \x01(\tR\bbuildLog\x12\x16\n" +
	"\x06binary\x18\x05 \x01(\fR\x06binary*\x8b\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14TASK_STATUS_COMPLETE\x10\x03\x12\x15\n" +
	"\x11TASK_STATUS_ERROR\x10\x04*_\n" +
	"\x11TransferDirection\x12\x18\n" +
	"\x14TRANSFER_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TRANSFER_TO_WORKER\x10\x01\x12\x18\n" +
	"\x14TRANSFER_FROM_WORKER\x10\x022\xa3\x01\n" +
	"\fOrchestrator\x12C\n" +
	"\bRegister\x12\x1a.distri.v1.RegisterRequest\x1a\x1b.distri.v1.RegisterResponse\x12N\n" +
	"\x0eControlChannel\x12\x18.distri.v1.WorkerMessage\x1a\x1e.distri.v1.OrchestratorMessage(\x010\x01B6Z4github.com/distribox/pkg/protocol/distri/v1;distriv1b\x06proto3"

var (
	file_distri_v1_control_proto_rawDescOnce sync.Once
	file_distri_v1_control_proto_rawDescData []byte
)

func file_distri_v1_control_proto_rawDescGZIP() []byte {
	file_distri_v1_control_proto_rawDescOnce.Do(func() {
		file_distri_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distri_v1_control_proto_rawDesc), len(file_distri_v1_control_proto_rawDesc)))
	})
	return file_distri_v1_control_proto_rawDescData
}

var file_distri_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_distri_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_distri_v1_control_proto_goTypes = []any{
	(TaskStatus)(0),             // 0: distri.v1.TaskStatus
	(TransferDirection)(0),      // 1: distri.v1.TransferDirection
	(*RegisterRequest)(nil),     // 2: distri.v1.RegisterRequest
	(*RegisterResponse)(nil),    // 3: distri.v1.RegisterResponse
	(*WorkerMessage)(nil),       // 4: distri.v1.WorkerMessage
	(*OrchestratorMessage)(nil), // 5: distri.v1.OrchestratorMessage
	(*Heartbeat)(nil),           // 6: distri.v1.Heartbeat
	(*HeartbeatAck)(nil),        // 7: distri.v1.HeartbeatAck
	(*Shutdown)(nil),            // 8: distri.v1.Shutdown
	(*TaskAssignment)(nil),      // 9: distri.v1.TaskAssignment
	(*TaskResult)(nil),          // 10: distri.v1.TaskResult
	(*BufferTransfer)(nil),      // 11: distri.v1.BufferTransfer
	(*CompileRequest)(nil),      // 12: distri.v1.CompileRequest
	(*CompileResult)(nil),       // 13: distri.v1.CompileResult
	(*CapabilityReport)(nil),    // 14: distri.v1.CapabilityReport
	(*ComputeTask)(nil),         // 15: distri.v1.ComputeTask
	(*BufferRegion)(nil),        // 16: distri.v1.BufferRegion
}
var file_distri_v1_control_proto_depIdxs = []int32{
	14, // 0: distri.v1.WorkerMessage.capability_update:type_name -> distri.v1.CapabilityReport
	10, // 1: distri.v1.WorkerMessage.task_result:type_name -> distri.v1.TaskResult
	6,  // 2: distri.v1.WorkerMessage.heartbeat:type_name -> distri.v1.Heartbeat
	13, // 3: distri.v1.WorkerMessage.compile_result:type_name -> distri.v1.CompileResult
	11, // 4: distri.v1.WorkerMessage.buffer:type_name -> distri.v1.BufferTransfer
	9,  // 5: distri.v1.OrchestratorMessage.task:type_name -> distri.v1.TaskAssignment
	12, // 6: distri.v1.OrchestratorMessage.compile:type_name -> distri.v1.CompileRequest
	11, // 7: distri.v1.OrchestratorMessage.buffer:type_name -> distri.v1.BufferTransfer
	7,  // 8: distri.v1.OrchestratorMessage.heartbeat_ack:type_name -> distri.v1.HeartbeatAck
	8,  // 9: distri.v1.OrchestratorMessage.shutdown:type_name -> distri.v1.Shutdown
	15, // 10: distri.v1.TaskAssignment.compute:type_name -> distri.v1.ComputeTask
	0,  // 11: distri.v1.TaskResult.status:type_name -> distri.v1.TaskStatus
	16, // 12: distri.v1.TaskResult.output_regions:type_name -> distri.v1.BufferRegion
	1,  // 13: distri.v1.BufferTransfer.direction:type_name -> distri.v1.TransferDirection
	2,  // 14: distri.v1.Orchestrator.Register:input_type -> distri.v1.RegisterRequest
	4,  // 15: distri.v1.Orchestrator.ControlChannel:input_type -> distri.v1.WorkerMessage
	3,  // 16: distri.v1.Orchestrator.Register:output_type -> distri.v1.RegisterResponse
	5,  // 17: distri.v1.Orchestrator.ControlChannel:output_type -> distri.v1.OrchestratorMessage
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_distri_v1_control_proto_init() }
func file_distri_v1_control_proto_init() {
	if File_distri_v1_control_proto != nil {
		return
	}
	file_distri_v1_capability_proto_init()
	file_distri_v1_compute_proto_init()
	file_distri_v1_control_proto_msgTypes[2].OneofWrappers = []any{
		(*WorkerMessage_CapabilityUpdate)(nil),
		(*WorkerMessage_TaskResult)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_CompileResult)(nil),
		(*WorkerMessage_Buffer)(nil),
	}
	file_distri_v1_control_proto_msgTypes[3].OneofWrappers = []any{
		(*OrchestratorMessage_Task)(nil),
		(*OrchestratorMessage_Compile)(nil),
		(*OrchestratorMessage_Buffer)(nil),
		(*OrchestratorMessage_HeartbeatAck)(nil),
		(*OrchestratorMessage_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distri_v1_control_proto_rawDesc), len(file_distri_v1_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distri_v1_control_proto_goTypes,
		DependencyIndexes: file_distri_v1_control_proto_depIdxs,
		EnumInfos:         file_distri_v1_control_proto_enumTypes,
		MessageInfos:      file_distri_v1_control_proto_msgTypes,
	}.Build()
	File_distri_v1_control_proto = out.File
	file_distri_v1_control_proto_goTypes = nil
	file_distri_v1_control_proto_depIdxs = nil
}
